[env]
BOBOT_LLM_BASE_URL = "https://api.z.ai/api/anthropic/v1"
BOBOT_LLM_MODEL = "GLM-4.7"

[tools]
go = { version = "1.25.5" }
"go:golang.org/x/tools/gopls" = { version = "v0.20.0" }
node = { version = "25.4.0" }
